package Mario;

public enum Type {

	MARIO, BRICK, MYSTERY, FLOOR, STAIR, PIT, PIPE_TL, PIPE_TR, PIPE_L, PIPE_R, FREE, BIGHILL, SMALLHILL, BIGBUSH,
	MEDBUSH, SMALLBUSH, COIN_MYSTERY, MUSHROOM_MYSTERY, FLOWER_MYSTERY, STAR_MYSTERY, LIFE_MYSTERY, COIN_BRICK,
	GOOMBA_START, KOOPA_START, // general mystery type
	COIN, MUSHROOM, FLOWER, STAR, LIFE, GOOMBA, KOOPA, NONE;

}